CREATE SCHEMA IF NOT EXISTS ffc;

create table individual
(
    id        bigint generated by default as identity
        primary key,
    active    boolean default true not null,
    uuid      varchar(40)          not null
        constraint uuid unique,
    email     varchar(50)          not null unique,
    firstname varchar(60)          not null,
    surname   varchar(60),
    password  varchar(100)         not null
);

comment on table individual is 'Пользователь';

comment on column individual.id is 'ID';

comment on column individual.active is 'Активация Пользователя';

comment on column individual.uuid is 'UUID';

comment on column individual.email is 'UserName';

comment on column individual.firstname is 'Имя Пользователя';

comment on column individual.surname is 'Фамилия Пользователя';

comment on column individual.password is 'Пароль';